# Use postgres/example user/password credentials

version: '3.3'

services:

  db:

    image: postgres

    restart: always

    environment:

      POSTGRES_DB: hotelManagement

      POSTGRES_USER: manager

      POSTGRES_PASSWORD: hotelmanagement

    ports:

      - "5432:5432"

    healthcheck:

      test: ["CMD-SHELL", "pg_isready"]

      interval: 10s

      timeout: 5s

      retries: 5



  adminer:

    image: adminer

    restart: always

    ports:

      - "8881:8080"